---

- name: Ansible Docker prerequisites
  pip:
    name: docker-py
    version: 1.10.6
    state: present

- name: Ensure gatling reports are empty
  file:
    path: "{{ gatling_host_dir }}"
    state: absent

- name: Create directory for gatling reports
  file:
    path: "{{ gatling_host_dir }}/results"
    state: directory

- name: Copy simulations to worker
  copy:
    src: "{{ playbook_dir }}/files/gatling_user_files/"
    dest: "{{ gatling_host_dir }}/user-files/"
