---

- name: Run Gatling
  docker_container:
    name: gatling-load-{{ inventory_hostname }}
    image: "{{ gatling_docker_image }}"
    state: started
    detach: false # By default this is true
    restart: true
    network_mode: host
    command:
      - --no-reports
      - --simulations-folder /gatling/user-files/simulations
      - --simulation {{ simulation_name }}
    volumes:
      - "{{ gatling_host_dir }}/results:/gatling/results"
      - "{{ gatling_host_dir }}/user-files:/gatling/user-files"

- name: Rename /tmp/gatling/results-{timustamp} to /tmp/gatling/results/results
  shell: ls -t {{ gatling_host_dir }}/results | head -n 1 | xargs -I {} mv {{ gatling_host_dir }}/results/{} {{ gatling_host_dir }}/results/results/
- name: Copy results
  fetch:
    src: "{{ gatling_host_dir }}/results/results/simulation.log"
    dest: "./results/simulation-{{ inventory_hostname }}.log"
    flat: true

