---
- name: Add SSH key to Vscale account
  run_once: true
  vscale_ssh:
    token: "{{ vscale_api_key }}"
    name: "Ansible"
    public_key: "{{ ssh_public_key }}"
    state: present
- name: Create scalet for inventory hosts
  vscale_scalets:
    token: "{{ vscale_api_key }}"
    name: "{{ inventory_hostname }}"
    plan: {{ vscale_plan }}
    location: {{ vscale_location }}
    image: {{ vscale_image }}
    key_name: "Ansible"
    collect_facts: "yes"
    power_state: "started"
    state: present
  register: server
- set_fact:
  ansible_ssh_host: "{{ server['scalet']['public_address']['address'] }}"
