---

- name: Prepare master
  hosts: local
  connection: local
  tasks:
    - include: tasks/prepare_master.yml

- name: Ensure public SSH key exists in VScale
  hosts: local
  connection: local
  vars_files:
    - vars/vscale.yml
  gather_facts: false
  tasks:
    - name: Add SSH key to Vscale account
      vscale_ssh:
        token: "{{ vscale_api_key }}"
        name: Ansible
        public_key: "{{ ssh_public_key }}"
        state: present

- name: Run simulation
  hosts: workers
  gather_facts: false
#  strategy: free # allows each host to run until the end of the play as fast as it can
  vars_files:
    - vars/vscale.yml
  tasks:
    - name: Create scalet for inventory hosts
      vscale_scalets:
        token: "{{ vscale_api_key }}"
        name: "{{ inventory_hostname }}"
        plan: "{{ vscale_plan }}"
        location: "{{ vscale_location }}"
        image: "{{ vscale_image }}"
        key_name: "Ansible"
        collect_facts: true
        power_state: started
        state: present
      register: server
      delegate_to: 127.0.0.1
    - set_fact:
        ansible_ssh_host: "{{ server['scalet']['public_address']['address'] }}"
    - name: Install python
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - python3
        - python3-pip
    - include: tasks/prepare_worker.yml
    - include: tasks/simulation.yml

- name: Generate report
  hosts: local
  connection: local
  tasks:
    - include: tasks/report.yml

- name: Clean up
  hosts: workers
  gather_facts: false
  tags:
    - cleanup
  vars_files:
    - vars/vscale.yml
  tasks:
    - name: Destroy scalets
      vscale_scalets:
        token: "{{ vscale_api_key }}"
        name: "{{ inventory_hostname }}"
        plan: "{{ vscale_plan }}"
        location: "{{ vscale_location }}"
        image: "{{ vscale_image }}"
        state: absent
      delegate_to: 127.0.0.1
