---

- name: Prepare master
  hosts: local
  connection: local
  tasks:
    - include: tasks/prepare_master.yml

- name: Ensure public SSH key exists in VScale
  hosts: local
  connection: local
  vars_files:
    - vars/vscale.yml
  gather_facts: false
  tasks:
    - name: Add SSH key to Vscale account
      vscale_ssh:
        token: "{{ vscale_api_key }}"
        name: Ansible
        public_key: "{{ ssh_public_key }}"
        state: present

- name: Slowly provision vscale in batches
  hosts: workers
  gather_facts: false
  serial: 10
  vars_files:
    - vars/vscale.yml
  tasks:
    - include: tasks/vscale_provision.yml

- name: Run simulation
  hosts: workers
  gather_facts: false
  strategy: free
  vars_files:
    - vars/vscale.yml
  tasks:
    # Need to be included to get ssh connection info
    - include: tasks/vscale_provision.yml
    - name: Install python
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - python3
        - python3-pip
    - include: tasks/prepare_worker.yml
    - include: tasks/simulation.yml

- name: Generate report
  hosts: local
  connection: local
  tasks:
    - include: tasks/report.yml

- name: Clean up
  hosts: workers
  gather_facts: false
  serial: 10
  tags:
    - cleanup
  vars_files:
    - vars/vscale.yml
  tasks:
    - name: Destroy scalets
      vscale_scalets:
        token: "{{ vscale_api_key }}"
        name: "{{ inventory_hostname }}"
        plan: "{{ vscale_plan }}"
        location: "{{ vscale_location }}"
        image: "{{ vscale_image }}"
        state: absent
      delegate_to: 127.0.0.1
